---
title: "UFO Sightings"
author: "Austin Mangelson"
format: html
editor: visual
---

```{r message=FALSE, warning=FALSE}
ufo_sightings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-06-20/ufo_sightings.csv')
places <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-06-20/places.csv')
day_parts_map <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-06-20/day_parts_map.csv')

```

```{r}
library(tidyverse)
library(ggplot2)
library(maps)
library(mapdata)
library(mapproj)
library(showtext)
library(ggimage)
library(packcircles)
library(ggpubr)
library(jpeg)
```

```{r}

places <- places |> 
  select(-alternate_city_names)

ufo_sightings <- ufo_sightings |> 
  left_join(places, by = c("city", "state", "country_code")) |> 
  mutate(shape = as.factor(shape))

contus_ufo_sightings <- ufo_sightings |> 
  filter(country == "USA", 
         !state %in% c("AK", "HI"),
         duration_seconds > 60)

airports <- read_csv("2023/2023-06-20/airports.csv")

```

```{r}
usa <- map_data("usa")
state <- map_data("state")

ggplot() + 
  geom_polygon(data = state, aes(x = long, y = lat, group = group),
               fill = "white", color = "black") +
  geom_point(data = contus_ufo_sightings, aes(x = longitude, y = latitude), color = "red") +
  guides(fill = FALSE) + 
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_blank(), 
        axis.ticks.x = element_blank(),
        axis.title.y = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.y = element_blank()) + 
  theme_void() +
  ggtitle('UFO Sightings') + 
  coord_fixed(1.3)
```

```{r}
contus_ufo_sightings |> 
  group_by(state) |> 
  summarise(total_sightings = n()) |> 
  arrange(desc(total_sightings))

ca_ufo_sightings <- ufo_sightings |> 
  filter(country == "USA",
         state == "CA",
         duration_seconds > 60)

ca_map <- state |> 
  filter(region == "california")

ca_airports <- airports |> 
  filter(STATE == "CA")

ggplot() + 
  geom_polygon(data = ca_map, aes(x = long, y = lat, group = group),
               fill = "white", color = "black") +
  geom_point(data = ca_ufo_sightings, aes(x = longitude, y = latitude), color = "red") +
  geom_point(data = ca_airports, aes(x = LONGITUDE, y = LATITUDE), color = "black", size = 2) +
  guides(fill = FALSE) + 
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_blank(), 
        axis.ticks.x = element_blank(),
        axis.title.y = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.y = element_blank()) + 
  theme_void() +
  #ggtitle('UFO Sightings') + 
  coord_fixed(1.3)
```

# UFO Shapes

```{r}

font_add_google(name = "Oxanium", family = "Oxanium")
showtext_auto()

url <- "https://t4.ftcdn.net/jpg/04/90/57/77/360_F_490577775_FJWG0sGo0OLoeBEcAIP4KSYjx1ofQ9o9.jpg"
download.file(url, destfile = "black_starry_sky.jpg")
img <- readJPEG("black_starry_sky.jpg")

ufo_shapes <- ufo_sightings |> 
  mutate(shape = case_when(
    shape %in% c("other", "unknown") ~ NA,
    shape %in% c("sphere", "orb") ~ "sphere",
    shape %in% c("egg", "oval") ~ "oval / egg",
    TRUE ~ shape
  )) |> 
  group_by(shape) |> 
  summarise(count = n()) |> 
  arrange(desc(count)) |> 
  head(11) |> 
  mutate(shape = str_to_title(shape)) |> 
  na.omit() |> 
  left_join(images, by = "shape")
    
g <- ggplot(ufo_shapes, aes(x = fct_reorder(shape, -count), y = count)) +
  geom_col(fill = "#31E721") +
  theme_minimal() +
  theme(
    axis.title = element_blank(),
    panel.grid = element_blank(),
    axis.text.x = element_text(
      angle = 40,
      hjust = 1,
      size = 11,
      family = "Oxanium",
      color = "#B0EC81"
    ),
    axis.text.y = element_blank(),
    legend.position = "none",
    plot.title = element_text(
      family = "Oxanium",
      size = 30,
      color = "#B0EC81",
      hjust = 0.5,
      vjust = -2.5
    ),
    plot.background = element_rect(fill = "black"),
    panel.background = element_rect(fill = "black")
  ) +
  labs(title = "Reported UFO Shapes")

  ggbackground(g, url)
```
